version: '3'

services:
    pripyatapi:
        build:
            context: .
            args:
                - PORT=${PORT}
        # Since we are building an image, we can give it a name.
        image: pripyat-srv 
        depends_on: 
            - pripyatdb
        environment:
            NODE_ENV: ${ENV}
            PORT: ${PORT}
            DB_USER: ${DB_APP_USER}
            DB_PASS: ${DB_APP_PASS}
            # SET LOCALLY TO KEEP THEM SAFE IN YOUR ENVIRONMENT AND NOT ON REPOSITORIES
            PM2_PUBLIC_KEY: ${PM2_PUBLIC_KEY}
            PM2_SECRET_KEY: ${PM2_SECRET_KEY}
        ports:
            - ${PUBLIC_PORT}:${PORT}
        container_name: 'pripyat-api'
        networks:
            - pripyat-network
    pripyatdb:
        image: postgres:alpine
        environment:
            POSTGRES_PASSWORD: ${DB_ADMIN_PASS}
        ports:
            - ${DB_PUBLIC_PORT}:${DB_PORT}
        container_name: 'pripyat-db'
        networks:
            - pripyat-network
            - pripyat-dba-network
    pripyatdb-admin:
        image: dpage/pgadmin4
        container_name: 'pripyat-dba'
        environment:
            PGADMIN_DEFAULT_EMAIL: ${DBA_LOGIN_EMAIL}
            PGADMIN_DEFAULT_PASSWORD: ${DBA_LOGIN_PASS}
        ports:
            - 8888:80
        networks:
            - pripyat-dba-network
networks:
    pripyat-network:
        driver: bridge
    pripyat-dba-network:
        driver: bridge